# Generated by Django 5.2.7 on 2025-10-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
