# Generated by Django 5.2.7 on 2025-10-08 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20251008_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name'], 'verbose_name': 'Лейбл', 'verbose_name_plural': 'Лейблы'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_year', 'title'], 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.AlterModelOptions(
            name='scrobble',
            options={'ordering': ['-scrobbled_at'], 'verbose_name': 'Прослушивание', 'verbose_name_plural': 'Прослушивания'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['release', 'position'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='catalog.track', verbose_name='Треки'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='catalog.artist', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='release',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='catalog.label', verbose_name='Лейбл'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobbles', to='catalog.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='scrobble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobbles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='catalog.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.release', verbose_name='Релиз'),
        ),
    ]
