# Generated by Django 5.2.7 on 2025-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_genre_options_alter_label_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус трека'),
        ),
    ]
