# Generated by Django 5.2.7 on 2025-11-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_playlist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='release',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Фото исполнителя'),
        ),
        migrations.AddField(
            model_name='release',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка релиза'),
        ),
    ]
