# Generated by Django 5.2.7 on 2025-11-06 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_artist_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='track',
            name='lyrics_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/lyrics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'doc', 'docx'])], verbose_name='Текст песни (файл)'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('contract', 'Контракт'), ('license', 'Лицензия'), ('sheet_music', 'Ноты'), ('chords', 'Аккорды'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'png'])], verbose_name='Файл документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
