# Generated by Django 5.2.7 on 2025-11-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_track_audio_file_track_lyrics_file_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Например: https://open.spotify.com/artist/...', verbose_name='Spotify'),
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, help_text='Например: https://artistname.com', verbose_name='Официальный сайт'),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Например: https://youtube.com/c/artistname', verbose_name='YouTube канал'),
        ),
        migrations.AddField(
            model_name='release',
            name='apple_music_url',
            field=models.URLField(blank=True, help_text='Ссылка на релиз в Apple Music', verbose_name='Apple Music'),
        ),
        migrations.AddField(
            model_name='release',
            name='bandcamp_url',
            field=models.URLField(blank=True, help_text='Ссылка на релиз в Bandcamp', verbose_name='Bandcamp'),
        ),
        migrations.AddField(
            model_name='release',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Ссылка на релиз в Spotify', verbose_name='Spotify'),
        ),
    ]
