# Generated by Django 5.2.7 on 2025-11-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_artist_spotify_url_artist_website_artist_youtube_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='artist',
            name='popularity_score',
            field=models.IntegerField(default=0, verbose_name='Популярность'),
        ),
        migrations.AddField(
            model_name='release',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый релиз'),
        ),
        migrations.AddField(
            model_name='release',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум релиз'),
        ),
        migrations.AddField(
            model_name='track',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый трек'),
        ),
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track', verbose_name='Трек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные треки',
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Неплохо'), (3, '3 - Хорошо'), (4, '4 - Очень хорошо'), (5, '5 - Отлично')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track', verbose_name='Трек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('user', 'track')},
            },
        ),
    ]
